# Generated by Django 4.2 on 2024-07-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=30)),
                ('director_name', models.CharField(max_length=30)),
                ('release_year', models.DateTimeField()),
                ('sinopsis', models.TextField(help_text='Ingresa un resumen de la película')),
            ],
        ),
    ]
